### ISSUE TITLE
Symlink not permitted. 

### ISSUE THREAD

**Issue by andrewfinnell** [fourlabsldn/dep-linker#2]
{ Error: EPERM: operation not permitted, symlink '[project]\node_modules\jquery' -> '[project]\src\js\deps\jquery'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',
  path: 'project\node_modules\jquery',
  dest: 'project\src\js\deps\jquery' }

It seems the module thinks it can use symlink even though it's on Windows. Does this module require intellij/gulp be run as Administrator? 

node --version 
v6.3.1

npm --version 
3.10.7

gulp --version
[09:12:03] CLI version 3.9.1
[09:12:03] Local version 3.9.1

**Comment by andrewfinnell** [comment]
I ran gulp from an Administrator console and it performed as expected. Is there a command option to NOT have it use symlinks and instead copy the dependencies? I suppose the module is named link-dependencies. but that seems like a risky solution. 

For anyone else that wants to be able to create symlinks without requiring Run as Administrator, we can enable Symlink creation using the following steps:
1. Run **gpedit.msc**
2.  _Computer Configuration_
3. _Windows Settings_
4. _Security Settings_
5. _Local Policies_
6. _User Rights Assignment_  
7. Edit '_Create symbolic links_' and add **Users** or your specific User Account.

**Comment by lazamar** [comment]
Unfortunately it currently doesn't have this option. When it was first implemented it copied instead of symlinking, we changed it later. If you look in the commits you can find the copying implementation. We accept pull requests :)

**Comment by lazamar** [comment]
Solved by 616c3632e32a5611f6a10e8d67f471f1feeee1a4
